version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DB=polls
    volumes:
      - polls_pg_data:/bitnami/postgresql
  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=docker
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - polls_redis_data:/bitnami/redis
volumes:
    polls_pg_data:
    polls_redis_data:
